// Production environment — generated by CI from GitHub Actions variable ANGULAR_BACKEND_URL.
// Do not edit manually. Local overrides belong in environment.ts.
export const environment = {
  apiBaseUrl: 'http://localhost:3001/api/ui/v1',
};
